List<Map<String, String>> codes = <Map<String, String>>[
  <String, String>{'name': 'Afghanistan', 'dial_code': '+93', 'code': 'AF'},
  <String, String>{'name': 'Aland Islands', 'dial_code': '+358', 'code': 'AX'},
  <String, String>{'name': 'Albania', 'dial_code': '+355', 'code': 'AL'},
  <String, String>{'name': 'Algeria', 'dial_code': '+213', 'code': 'DZ'},
  <String, String>{'name': 'AmericanSamoa', 'dial_code': '+1 684', 'code': 'AS'},
  <String, String>{'name': 'Andorra', 'dial_code': '+376', 'code': 'AD'},
  <String, String>{'name': 'Angola', 'dial_code': '+244', 'code': 'AO'},
  <String, String>{'name': 'Anguilla', 'dial_code': '+1 264', 'code': 'AI'},
  <String, String>{'name': 'Antarctica', 'dial_code': '+672', 'code': 'AQ'},
  <String, String>{'name': 'Antigua and Barbuda', 'dial_code': '+1268', 'code': 'AG'},
  <String, String>{'name': 'Argentina', 'dial_code': '+54', 'code': 'AR'},
  <String, String>{'name': 'Armenia', 'dial_code': '+374', 'code': 'AM'},
  <String, String>{'name': 'Aruba', 'dial_code': '+297', 'code': 'AW'},
  <String, String>{'name': 'Australia', 'dial_code': '+61', 'code': 'AU'},
  <String, String>{'name': 'Austria', 'dial_code': '+43', 'code': 'AT'},
  <String, String>{'name': 'Azerbaijan', 'dial_code': '+994', 'code': 'AZ'},
  <String, String>{'name': 'Bahamas', 'dial_code': '+1 242', 'code': 'BS'},
  <String, String>{'name': 'Bahrain', 'dial_code': '+973', 'code': 'BH'},
  <String, String>{'name': 'Bangladesh', 'dial_code': '+880', 'code': 'BD'},
  <String, String>{'name': 'Barbados', 'dial_code': '+1 246', 'code': 'BB'},
  <String, String>{'name': 'Belarus', 'dial_code': '+375', 'code': 'BY'},
  <String, String>{'name': 'Belgium', 'dial_code': '+32', 'code': 'BE'},
  <String, String>{'name': 'Belize', 'dial_code': '+501', 'code': 'BZ'},
  <String, String>{'name': 'Benin', 'dial_code': '+229', 'code': 'BJ'},
  <String, String>{'name': 'Bermuda', 'dial_code': '+1 441', 'code': 'BM'},
  <String, String>{'name': 'Bhutan', 'dial_code': '+975', 'code': 'BT'},
  <String, String>{'name': 'Bolivia, Plurinational State of', 'dial_code': '+591', 'code': 'BO'},
  <String, String>{'name': 'Bosnia and Herzegovina', 'dial_code': '+387', 'code': 'BA'},
  <String, String>{'name': 'Botswana', 'dial_code': '+267', 'code': 'BW'},
  <String, String>{'name': 'Brazil', 'dial_code': '+55', 'code': 'BR'},
  <String, String>{'name': 'British Indian Ocean Territory', 'dial_code': '+246', 'code': 'IO'},
  <String, String>{'name': 'Brunei Darussalam', 'dial_code': '+673', 'code': 'BN'},
  <String, String>{'name': 'Bulgaria', 'dial_code': '+359', 'code': 'BG'},
  <String, String>{'name': 'Burkina Faso', 'dial_code': '+226', 'code': 'BF'},
  <String, String>{'name': 'Burundi', 'dial_code': '+257', 'code': 'BI'},
  <String, String>{'name': 'Cambodia', 'dial_code': '+855', 'code': 'KH'},
  <String, String>{'name': 'Cameroon', 'dial_code': '+237', 'code': 'CM'},
  <String, String>{'name': 'Canada', 'dial_code': '+1', 'code': 'CA'},
  <String, String>{'name': 'Cape Verde', 'dial_code': '+238', 'code': 'CV'},
  <String, String>{'name': 'Cayman Islands', 'dial_code': '+ 345', 'code': 'KY'},
  <String, String>{'name': 'Central African Republic', 'dial_code': '+236', 'code': 'CF'},
  <String, String>{'name': 'Chad', 'dial_code': '+235', 'code': 'TD'},
  <String, String>{'name': 'Chile', 'dial_code': '+56', 'code': 'CL'},
  <String, String>{'name': 'China', 'dial_code': '+86', 'code': 'CN'},
  <String, String>{'name': 'Christmas Island', 'dial_code': '+61', 'code': 'CX'},
  <String, String>{'name': 'Cocos (Keeling) Islands', 'dial_code': '+61', 'code': 'CC'},
  <String, String>{'name': 'Colombia', 'dial_code': '+57', 'code': 'CO'},
  <String, String>{'name': 'Comoros', 'dial_code': '+269', 'code': 'KM'},
  <String, String>{'name': 'Congo', 'dial_code': '+242', 'code': 'CG'},
  <String, String>{
    'name': 'Congo, The Democratic Republic of the Congo',
    'dial_code': '+243',
    'code': 'CD'
  },
  <String, String>{'name': 'Cook Islands', 'dial_code': '+682', 'code': 'CK'},
  <String, String>{'name': 'Costa Rica', 'dial_code': '+506', 'code': 'CR'},
  <String, String>{'name': 'Cote d\'Ivoire', 'dial_code': '+225', 'code': 'CI'},
  <String, String>{'name': 'Croatia', 'dial_code': '+385', 'code': 'HR'},
  <String, String>{'name': 'Cuba', 'dial_code': '+53', 'code': 'CU'},
  <String, String>{'name': 'Cyprus', 'dial_code': '+357', 'code': 'CY'},
  <String, String>{'name': 'Czech Republic', 'dial_code': '+420', 'code': 'CZ'},
  <String, String>{'name': 'Denmark', 'dial_code': '+45', 'code': 'DK'},
  <String, String>{'name': 'Djibouti', 'dial_code': '+253', 'code': 'DJ'},
  <String, String>{'name': 'Dominica', 'dial_code': '+1 767', 'code': 'DM'},
  <String, String>{'name': 'Dominican Republic', 'dial_code': '+1 849', 'code': 'DO'},
  <String, String>{'name': 'Ecuador', 'dial_code': '+593', 'code': 'EC'},
  <String, String>{'name': 'Egypt', 'dial_code': '+20', 'code': 'EG'},
  <String, String>{'name': 'El Salvador', 'dial_code': '+503', 'code': 'SV'},
  <String, String>{'name': 'Equatorial Guinea', 'dial_code': '+240', 'code': 'GQ'},
  <String, String>{'name': 'Eritrea', 'dial_code': '+291', 'code': 'ER'},
  <String, String>{'name': 'Estonia', 'dial_code': '+372', 'code': 'EE'},
  <String, String>{'name': 'Ethiopia', 'dial_code': '+251', 'code': 'ET'},
  <String, String>{'name': 'Falkland Islands (Malvinas)', 'dial_code': '+500', 'code': 'FK'},
  <String, String>{'name': 'Faroe Islands', 'dial_code': '+298', 'code': 'FO'},
  <String, String>{'name': 'Fiji', 'dial_code': '+679', 'code': 'FJ'},
  <String, String>{'name': 'Finland', 'dial_code': '+358', 'code': 'FI'},
  <String, String>{'name': 'France', 'dial_code': '+33', 'code': 'FR'},
  <String, String>{'name': 'French Guiana', 'dial_code': '+594', 'code': 'GF'},
  <String, String>{'name': 'French Polynesia', 'dial_code': '+689', 'code': 'PF'},
  <String, String>{'name': 'Gabon', 'dial_code': '+241', 'code': 'GA'},
  <String, String>{'name': 'Gambia', 'dial_code': '+220', 'code': 'GM'},
  <String, String>{'name': 'Georgia', 'dial_code': '+995', 'code': 'GE'},
  <String, String>{'name': 'Germany', 'dial_code': '+49', 'code': 'DE'},
  <String, String>{'name': 'Ghana', 'dial_code': '+233', 'code': 'GH'},
  <String, String>{'name': 'Gibraltar', 'dial_code': '+350', 'code': 'GI'},
  <String, String>{'name': 'Greece', 'dial_code': '+30', 'code': 'GR'},
  <String, String>{'name': 'Greenland', 'dial_code': '+299', 'code': 'GL'},
  <String, String>{'name': 'Grenada', 'dial_code': '+1 473', 'code': 'GD'},
  <String, String>{'name': 'Guadeloupe', 'dial_code': '+590', 'code': 'GP'},
  <String, String>{'name': 'Guam', 'dial_code': '+1 671', 'code': 'GU'},
  <String, String>{'name': 'Guatemala', 'dial_code': '+502', 'code': 'GT'},
  <String, String>{'name': 'Guernsey', 'dial_code': '+44', 'code': 'GG'},
  <String, String>{'name': 'Guinea', 'dial_code': '+224', 'code': 'GN'},
  <String, String>{'name': 'Guinea-Bissau', 'dial_code': '+245', 'code': 'GW'},
  <String, String>{'name': 'Guyana', 'dial_code': '+595', 'code': 'GY'},
  <String, String>{'name': 'Haiti', 'dial_code': '+509', 'code': 'HT'},
  <String, String>{'name': 'Holy See (Vatican City State)', 'dial_code': '+379', 'code': 'VA'},
  <String, String>{'name': 'Honduras', 'dial_code': '+504', 'code': 'HN'},
  <String, String>{'name': 'Hong Kong', 'dial_code': '+852', 'code': 'HK'},
  <String, String>{'name': 'Hungary', 'dial_code': '+36', 'code': 'HU'},
  <String, String>{'name': 'Iceland', 'dial_code': '+354', 'code': 'IS'},
  <String, String>{'name': 'India', 'dial_code': '+91', 'code': 'IN'},
  <String, String>{'name': 'Indonesia', 'dial_code': '+62', 'code': 'ID'},
  <String, String>{
    'name': 'Iran, Islamic Republic of Persian Gulf',
    'dial_code': '+98',
    'code': 'IR'
  },
  <String, String>{'name': 'Iraq', 'dial_code': '+964', 'code': 'IQ'},
  <String, String>{'name': 'Ireland', 'dial_code': '+353', 'code': 'IE'},
  <String, String>{'name': 'Isle of Man', 'dial_code': '+44', 'code': 'IM'},
  <String, String>{'name': 'Israel', 'dial_code': '+972', 'code': 'IL'},
  <String, String>{'name': 'Italy', 'dial_code': '+39', 'code': 'IT'},
  <String, String>{'name': 'Jamaica', 'dial_code': '+1 876', 'code': 'JM'},
  <String, String>{'name': 'Japan', 'dial_code': '+81', 'code': 'JP'},
  <String, String>{'name': 'Jersey', 'dial_code': '+44', 'code': 'JE'},
  <String, String>{'name': 'Jordan', 'dial_code': '+962', 'code': 'JO'},
  <String, String>{'name': 'Kazakhstan', 'dial_code': '+7 7', 'code': 'KZ'},
  <String, String>{'name': 'Kenya', 'dial_code': '+254', 'code': 'KE'},
  <String, String>{'name': 'Kiribati', 'dial_code': '+686', 'code': 'KI'},
  <String, String>{
    'name': 'Korea, Democratic People\'s Republic of Korea',
    'dial_code': '+850',
    'code': 'KP'
  },
  <String, String>{'name': 'Korea, Republic of South Korea', 'dial_code': '+82', 'code': 'KR'},
  <String, String>{'name': 'Kuwait', 'dial_code': '+965', 'code': 'KW'},
  <String, String>{'name': 'Kyrgyzstan', 'dial_code': '+996', 'code': 'KG'},
  <String, String>{'name': 'Laos', 'dial_code': '+856', 'code': 'LA'},
  <String, String>{'name': 'Latvia', 'dial_code': '+371', 'code': 'LV'},
  <String, String>{'name': 'Lebanon', 'dial_code': '+961', 'code': 'LB'},
  <String, String>{'name': 'Lesotho', 'dial_code': '+266', 'code': 'LS'},
  <String, String>{'name': 'Liberia', 'dial_code': '+231', 'code': 'LR'},
  <String, String>{'name': 'Libyan Arab Jamahiriya', 'dial_code': '+218', 'code': 'LY'},
  <String, String>{'name': 'Liechtenstein', 'dial_code': '+423', 'code': 'LI'},
  <String, String>{'name': 'Lithuania', 'dial_code': '+370', 'code': 'LT'},
  <String, String>{'name': 'Luxembourg', 'dial_code': '+352', 'code': 'LU'},
  <String, String>{'name': 'Macao', 'dial_code': '+853', 'code': 'MO'},
  <String, String>{'name': 'Macedonia', 'dial_code': '+389', 'code': 'MK'},
  <String, String>{'name': 'Madagascar', 'dial_code': '+261', 'code': 'MG'},
  <String, String>{'name': 'Malawi', 'dial_code': '+265', 'code': 'MW'},
  <String, String>{'name': 'Malaysia', 'dial_code': '+60', 'code': 'MY'},
  <String, String>{'name': 'Maldives', 'dial_code': '+960', 'code': 'MV'},
  <String, String>{'name': 'Mali', 'dial_code': '+223', 'code': 'ML'},
  <String, String>{'name': 'Malta', 'dial_code': '+356', 'code': 'MT'},
  <String, String>{'name': 'Marshall Islands', 'dial_code': '+692', 'code': 'MH'},
  <String, String>{'name': 'Martinique', 'dial_code': '+596', 'code': 'MQ'},
  <String, String>{'name': 'Mauritania', 'dial_code': '+222', 'code': 'MR'},
  <String, String>{'name': 'Mauritius', 'dial_code': '+230', 'code': 'MU'},
  <String, String>{'name': 'Mayotte', 'dial_code': '+262', 'code': 'YT'},
  <String, String>{'name': 'Mexico', 'dial_code': '+52', 'code': 'MX'},
  <String, String>{
    'name': 'Micronesia, Federated States of Micronesia',
    'dial_code': '+691',
    'code': 'FM'
  },
  <String, String>{'name': 'Moldova', 'dial_code': '+373', 'code': 'MD'},
  <String, String>{'name': 'Monaco', 'dial_code': '+377', 'code': 'MC'},
  <String, String>{'name': 'Mongolia', 'dial_code': '+976', 'code': 'MN'},
  <String, String>{'name': 'Montenegro', 'dial_code': '+382', 'code': 'ME'},
  <String, String>{'name': 'Montserrat', 'dial_code': '+1664', 'code': 'MS'},
  <String, String>{'name': 'Morocco', 'dial_code': '+212', 'code': 'MA'},
  <String, String>{'name': 'Mozambique', 'dial_code': '+258', 'code': 'MZ'},
  <String, String>{'name': 'Myanmar', 'dial_code': '+95', 'code': 'MM'},
  <String, String>{'name': 'Namibia', 'dial_code': '+264', 'code': 'NA'},
  <String, String>{'name': 'Nauru', 'dial_code': '+674', 'code': 'NR'},
  <String, String>{'name': 'Nepal', 'dial_code': '+977', 'code': 'NP'},
  <String, String>{'name': 'Netherlands', 'dial_code': '+31', 'code': 'NL'},
  <String, String>{'name': 'Netherlands Antilles', 'dial_code': '+599', 'code': 'AN'},
  <String, String>{'name': 'New Caledonia', 'dial_code': '+687', 'code': 'NC'},
  <String, String>{'name': 'New Zealand', 'dial_code': '+64', 'code': 'NZ'},
  <String, String>{'name': 'Nicaragua', 'dial_code': '+505', 'code': 'NI'},
  <String, String>{'name': 'Niger', 'dial_code': '+227', 'code': 'NE'},
  <String, String>{'name': 'Nigeria', 'dial_code': '+234', 'code': 'NG'},
  <String, String>{'name': 'Niue', 'dial_code': '+683', 'code': 'NU'},
  <String, String>{'name': 'Norfolk Island', 'dial_code': '+672', 'code': 'NF'},
  <String, String>{'name': 'Northern Mariana Islands', 'dial_code': '+1 670', 'code': 'MP'},
  <String, String>{'name': 'Norway', 'dial_code': '+47', 'code': 'NO'},
  <String, String>{'name': 'Oman', 'dial_code': '+968', 'code': 'OM'},
  <String, String>{'name': 'Pakistan', 'dial_code': '+92', 'code': 'PK'},
  <String, String>{'name': 'Palau', 'dial_code': '+680', 'code': 'PW'},
  <String, String>{'name': 'Palestinian Territory, Occupied', 'dial_code': '+970', 'code': 'PS'},
  <String, String>{'name': 'Panama', 'dial_code': '+507', 'code': 'PA'},
  <String, String>{'name': 'Papua New Guinea', 'dial_code': '+675', 'code': 'PG'},
  <String, String>{'name': 'Paraguay', 'dial_code': '+595', 'code': 'PY'},
  <String, String>{'name': 'Peru', 'dial_code': '+51', 'code': 'PE'},
  <String, String>{'name': 'Philippines', 'dial_code': '+63', 'code': 'PH'},
  <String, String>{'name': 'Pitcairn', 'dial_code': '+872', 'code': 'PN'},
  <String, String>{'name': 'Poland', 'dial_code': '+48', 'code': 'PL'},
  <String, String>{'name': 'Portugal', 'dial_code': '+351', 'code': 'PT'},
  <String, String>{'name': 'Puerto Rico', 'dial_code': '+1 939', 'code': 'PR'},
  <String, String>{'name': 'Qatar', 'dial_code': '+974', 'code': 'QA'},
  <String, String>{'name': 'Romania', 'dial_code': '+40', 'code': 'RO'},
  <String, String>{'name': 'Russia', 'dial_code': '+7', 'code': 'RU'},
  <String, String>{'name': 'Rwanda', 'dial_code': '+250', 'code': 'RW'},
  <String, String>{'name': 'Reunion', 'dial_code': '+262', 'code': 'RE'},
  <String, String>{'name': 'Saint Barthelemy', 'dial_code': '+590', 'code': 'BL'},
  <String, String>{
    'name': 'Saint Helena, Ascension and Tristan Da Cunha',
    'dial_code': '+290',
    'code': 'SH'
  },
  <String, String>{'name': 'Saint Kitts and Nevis', 'dial_code': '+1 869', 'code': 'KN'},
  <String, String>{'name': 'Saint Lucia', 'dial_code': '+1 758', 'code': 'LC'},
  <String, String>{'name': 'Saint Martin', 'dial_code': '+590', 'code': 'MF'},
  <String, String>{'name': 'Saint Pierre and Miquelon', 'dial_code': '+508', 'code': 'PM'},
  <String, String>{'name': 'Saint Vincent and the Grenadines', 'dial_code': '+1 784', 'code': 'VC'},
  <String, String>{'name': 'Samoa', 'dial_code': '+685', 'code': 'WS'},
  <String, String>{'name': 'San Marino', 'dial_code': '+378', 'code': 'SM'},
  <String, String>{'name': 'Sao Tome and Principe', 'dial_code': '+239', 'code': 'ST'},
  <String, String>{'name': 'Saudi Arabia', 'dial_code': '+966', 'code': 'SA'},
  <String, String>{'name': 'Senegal', 'dial_code': '+221', 'code': 'SN'},
  <String, String>{'name': 'Serbia', 'dial_code': '+381', 'code': 'RS'},
  <String, String>{'name': 'Seychelles', 'dial_code': '+248', 'code': 'SC'},
  <String, String>{'name': 'Sierra Leone', 'dial_code': '+232', 'code': 'SL'},
  <String, String>{'name': 'Singapore', 'dial_code': '+65', 'code': 'SG'},
  <String, String>{'name': 'Slovakia', 'dial_code': '+421', 'code': 'SK'},
  <String, String>{'name': 'Slovenia', 'dial_code': '+386', 'code': 'SI'},
  <String, String>{'name': 'Solomon Islands', 'dial_code': '+677', 'code': 'SB'},
  <String, String>{'name': 'Somalia', 'dial_code': '+252', 'code': 'SO'},
  <String, String>{'name': 'South Africa', 'dial_code': '+27', 'code': 'ZA'},
  <String, String>{
    'name': 'South Georgia and the South Sandwich Islands',
    'dial_code': '+500',
    'code': 'GS'
  },
  <String, String>{'name': 'Spain', 'dial_code': '+34', 'code': 'ES'},
  <String, String>{'name': 'Sri Lanka', 'dial_code': '+94', 'code': 'LK'},
  <String, String>{'name': 'Sudan', 'dial_code': '+249', 'code': 'SD'},
  <String, String>{'name': 'Suriname', 'dial_code': '+597', 'code': 'SR'},
  <String, String>{'name': 'Svalbard and Jan Mayen', 'dial_code': '+47', 'code': 'SJ'},
  <String, String>{'name': 'Swaziland', 'dial_code': '+268', 'code': 'SZ'},
  <String, String>{'name': 'Sweden', 'dial_code': '+46', 'code': 'SE'},
  <String, String>{'name': 'Switzerland', 'dial_code': '+41', 'code': 'CH'},
  <String, String>{'name': 'Syrian Arab Republic', 'dial_code': '+963', 'code': 'SY'},
  <String, String>{'name': 'Taiwan', 'dial_code': '+886', 'code': 'TW'},
  <String, String>{'name': 'Tajikistan', 'dial_code': '+992', 'code': 'TJ'},
  <String, String>{
    'name': 'Tanzania, United Republic of Tanzania',
    'dial_code': '+255',
    'code': 'TZ'
  },
  <String, String>{'name': 'Thailand', 'dial_code': '+66', 'code': 'TH'},
  <String, String>{'name': 'Timor-Leste', 'dial_code': '+670', 'code': 'TL'},
  <String, String>{'name': 'Togo', 'dial_code': '+228', 'code': 'TG'},
  <String, String>{'name': 'Tokelau', 'dial_code': '+690', 'code': 'TK'},
  <String, String>{'name': 'Tonga', 'dial_code': '+676', 'code': 'TO'},
  <String, String>{'name': 'Trinidad and Tobago', 'dial_code': '+1 868', 'code': 'TT'},
  <String, String>{'name': 'Tunisia', 'dial_code': '+216', 'code': 'TN'},
  <String, String>{'name': 'Turkey', 'dial_code': '+90', 'code': 'TR'},
  <String, String>{'name': 'Turkmenistan', 'dial_code': '+993', 'code': 'TM'},
  <String, String>{'name': 'Turks and Caicos Islands', 'dial_code': '+1 649', 'code': 'TC'},
  <String, String>{'name': 'Tuvalu', 'dial_code': '+688', 'code': 'TV'},
  <String, String>{'name': 'Uganda', 'dial_code': '+256', 'code': 'UG'},
  <String, String>{'name': 'Ukraine', 'dial_code': '+380', 'code': 'UA'},
  <String, String>{'name': 'United Arab Emirates', 'dial_code': '+971', 'code': 'AE'},
  <String, String>{'name': 'United Kingdom', 'dial_code': '+44', 'code': 'GB'},
  <String, String>{'name': 'United States', 'dial_code': '+1', 'code': 'US'},
  <String, String>{'name': 'Uruguay', 'dial_code': '+598', 'code': 'UY'},
  <String, String>{'name': 'Uzbekistan', 'dial_code': '+998', 'code': 'UZ'},
  <String, String>{'name': 'Vanuatu', 'dial_code': '+678', 'code': 'VU'},
  <String, String>{
    'name': 'Venezuela, Bolivarian Republic of Venezuela',
    'dial_code': '+58',
    'code': 'VE'
  },
  <String, String>{'name': 'Vietnam', 'dial_code': '+84', 'code': 'VN'},
  <String, String>{'name': 'Virgin Islands, British', 'dial_code': '+1 284', 'code': 'VG'},
  <String, String>{'name': 'Virgin Islands, U.S.', 'dial_code': '+1 340', 'code': 'VI'},
  <String, String>{'name': 'Wallis and Futuna', 'dial_code': '+681', 'code': 'WF'},
  <String, String>{'name': 'Yemen', 'dial_code': '+967', 'code': 'YE'},
  <String, String>{'name': 'Zambia', 'dial_code': '+260', 'code': 'ZM'},
  <String, String>{'name': 'Zimbabwe', 'dial_code': '+263', 'code': 'ZW'}
];
